apache_servers:
  hosts:
    local_fedora_vm:
      ansible_host: localhost
      ansible_port: 2222
      ansible_user: root
      apache_package: httpd-2.4.54
      apache_service: httpd
      php_package: php-8.1.9
    local_gcp_debian_vm:
      ansible_host: localhost
      ansible_port: 22
      ansible_user: "{{ lookup('env', 'USER') }}"
      apache_package: apache2
      apache_service: apache2
      php_package: php7.4
